services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PG_DATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
