name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
